version: "3.8"

services:
  frontend:
    build:
      context: ./exerciseFrontend
    ports:
      - "4200:4200"
    volumes:
      - ./exerciseFrontend/src:/frontend/src
  backend:
    build:
      context: ./server
    ports:
      - "3030:3030"
    volumes:
      - ./server/:/backend/
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
