version: "3.8"

services:
  frontend:
    build:
      context: ./exerciseFrontend
    ports:
      - "4200:4200"
    volumes:
      - ./exerciseFrontend/src:/frontend/src
  backend:
    build:
      context: ./server
    ports:
      - "3030:3030"
    volumes:
      - ./server/:/backend/

